// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Infrastructure.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260502152048_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Core.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_mode");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<string>("TokenJson")
                        .HasColumnType("text")
                        .HasColumnName("token_json");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType")
                        .HasDatabaseName("ix_integrations_service_type");

                    b.ToTable("integrations", (string)null);
                });

            modelBuilder.Entity("Nexus.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Nexus.Core.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fire_at");

                    b.Property<bool>("IsFired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fired");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("FireAt")
                        .HasDatabaseName("ix_reminders_fire_at");

                    b.HasIndex("IsFired")
                        .HasDatabaseName("ix_reminders_is_fired");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_reminders_task_id");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Nexus.Core.Entities.ServiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_json");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_items_service_type_external_id");

                    b.ToTable("service_items", (string)null);
                });

            modelBuilder.Entity("Nexus.Core.Entities.SyncCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cursor")
                        .HasColumnType("text")
                        .HasColumnName("cursor");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_checkpoints_service_type");

                    b.ToTable("sync_checkpoints", (string)null);
                });

            modelBuilder.Entity("Nexus.Core.Entities.UnifiedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("SyncFromSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("sync_from_source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_unified_tasks_due_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_unified_tasks_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_unified_tasks_status");

                    b.ToTable("unified_tasks", (string)null);
                });

            modelBuilder.Entity("Nexus.Core.Entities.Project", b =>
                {
                    b.OwnsOne("Nexus.Core.ValueObjects.ExternalRef", "ExternalRef", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_id");

                            b1.Property<Guid?>("IntegrationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ProjectKey")
                                .HasColumnType("text")
                                .HasColumnName("external_project_key");

                            b1.Property<string>("ServiceType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_service_type");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_url");

                            b1.HasKey("ProjectId");

                            b1.ToTable("projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("ExternalRef");
                });

            modelBuilder.Entity("Nexus.Core.Entities.UnifiedTask", b =>
                {
                    b.OwnsOne("Nexus.Core.ValueObjects.ExternalRef", "ExternalRef", b1 =>
                        {
                            b1.Property<Guid>("UnifiedTaskId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExternalId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_id");

                            b1.Property<Guid?>("IntegrationId")
                                .HasColumnType("uuid")
                                .HasColumnName("external_integration_id");

                            b1.Property<string>("ProjectKey")
                                .HasColumnType("text")
                                .HasColumnName("external_project_key");

                            b1.Property<string>("ServiceType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_service_type");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("external_url");

                            b1.HasKey("UnifiedTaskId");

                            b1.ToTable("unified_tasks");

                            b1.WithOwner()
                                .HasForeignKey("UnifiedTaskId");
                        });

                    b.Navigation("ExternalRef");
                });
#pragma warning restore 612, 618
        }
    }
}
