<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>869b7ba2-1187-4ea4-bc4e-dd9ddc856439</UserSecretsId>
    <ContainerRegistry>ghcr.io</ContainerRegistry>
    <ContainerRepository>ghcr.io/khuongntrd/nexus</ContainerRepository>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Nexus.Core/Nexus.Core.csproj" />
    <ProjectReference Include="../Nexus.Application/Nexus.Application.csproj" />
    <ProjectReference Include="../Nexus.Infrastructure/Nexus.Infrastructure.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.Core/Nexus.Connectors.Core.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.GitHub/Nexus.Connectors.GitHub.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.Jira/Nexus.Connectors.Jira.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.MicrosoftTodo/Nexus.Connectors.MicrosoftTodo.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.GitHub.Components/Nexus.Connectors.GitHub.Components.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.Jira.Components/Nexus.Connectors.Jira.Components.csproj" />
    <ProjectReference Include="../Nexus.Connectors/Nexus.Connectors.MicrosoftTodo.Components/Nexus.Connectors.MicrosoftTodo.Components.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" />
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Keys" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Quartz.Extensions.Hosting" />
  </ItemGroup>

</Project>
